### ISSUE TITLE
terminals database is inaccessible

### ISSUE THREAD

**Issue by adictovirtual** [nicknisi/dotfiles#33] opened 2016-09-07 22:22 UTC
newbie advice 🙊

after i run ` install.sh` in my OSX El Capitan getting 
`terminals database is inaccessible` after i hit `clear` at the console any advice

**Comment by nicknisi** [comment] 2016-09-08 21:46
This is likely caused by the terminfo settings I created for italic font support (for [Operator Mono](http://www.typography.com/blog/introducing-operator)). You can either change your `$TERM` to something like `xterm-256color` or you can install the italic terminfo with the following commands from the project root directory:

```
tic resources/xterm-256color-italic.terminfo
tic resources/tmux-256color-italic.terminfo
```

Hope this helps!

**Comment by nicknisi** [comment] 2016-09-23 00:25
Going to close this for now. Please reopen if you're still having issues. Thanks!

**Closed by nicknisi** 2016-09-23 00:25 UTC
