### ISSUE TITLE
Nvim config throws error

### ISSUE THREAD

**Issue by rubiin** [nicknisi/dotfiles#177] opened 2021-05-06 15:26 UTC
I am trying to use your nvim config and have cloned your repo and copied the nvim dir to .config in my system. When I do , nvim i get errors like in here https://i.imgur.com/OEi7tHD.png

**Comment by nicknisi** [comment] 2021-05-06 15:35
Try running `nvim +PlugInstall`

**Comment by rubiin** [comment] 2021-05-06 16:12
the plugins get installed however on coc i get https://i.imgur.com/a5U5TNr.png

**Comment by nicknisi** [comment] 2021-05-06 16:28
Hmm, interesting. There could be a couple of reasons for this. First off, it might work on the next time you load vim. If that doesn't work, try running `nvim +checkhealth` and show the output. You might need to install the `neovim` node package (`npm i -g neovim`).

**Comment by rubiin** [comment] 2021-05-27 17:21
@nicknisi  that solved the issue. Another thing is nerd tree included in here

**Comment by nicknisi** [comment] 2021-05-27 17:24
NERDTree is not included in this setup. Instead, I'm using [coc-explorer](https://github.com/weirongxu/coc-explorer) which can be toggled via `,k`.

**Comment by rubiin** [comment] 2021-05-27 18:25
> NERDTree is not included in this setup. Instead, I'm using [coc-explorer](https://github.com/weirongxu/coc-explorer) which can be toggled via `,k`.

Thanks man. Love the nvim setup, saved me from the hassle of configuring myself and has everything I wished for .Keep adding

**Comment by nicknisi** [comment] 2021-05-31 03:21
Awesome, thank you! I'm going to close this as the issue is resolved, but feel free to open more issues or start new [discussions](https://github.com/nicknisi/dotfiles/discussions/new) if you have more questions. Thanks.

**Closed by nicknisi** 2021-05-31 03:21 UTC
